baseurl: "/"
languageCode: "en-us"
title: "Homepage"

DefaultContentLanguage: en
copyright: BOGITAL
enableRobotsTXT: true

languages:
  en:
    contentDir: content/en
    languageName: English
    params:
      logoURL: /img/logo.svg
    title: My blog
    weight: 1
    menu:
      main:
        - identifier: home
          name: Home
          url: /
          weight: -110
        - name: Blog
          # post: <span class='alert'>New!</span>
          # pre: <i class='fa fa-road'></i>
          url: /blog
          weight: -100
  fr:
    contentDir: content/fr
    languageName: Français
    params:
      logoURL: /img/logo.svg
      navigation:
        help: Aide
    title: Mon blogue
    menu:
      main:
        - identifier: home
          name: Home
          url: /fr
          weight: -110
        - name: Blog
          # post: <span class='alert'>New!</span>
          # pre: <i class='fa fa-road'></i>
          url: /fr/blog
          weight: -100
sitemap:
    path: sitemap.xml
    tag: false
    category: false
    changefreq: weekly
    filename: sitemap.xml
    priority: 0.5